DROP TABLE IF EXISTS taches;

CREATE TABLE taches (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    titre TEXT NOT NULL,
    description TEXT,
    date_echeance TEXT,
    est_terminee BOOLEAN DEFAULT 0
);
